### ISSUE TITLE
[feat] dark mode, text theme 적용하기

### ISSUE THREAD

**Issue by leesunmin1231** [broadenHorizon/math_skill_up#2]
# 설명
- 현재 appbar에 있는 icon으로 다크모드 온/오프가 가능하도록 구현되어 있음.
- 추후 설정에서 변경할 수 있도록 수정 필요함.
- dark mode 스위치 구현 방법은 top_bar.dart에 구현되어 있는 코드 참조.
- 현재 dark mode인지 light mode인지 알 수 있는 값을 가져오는 방법은 아래와 같다.
```dart
ValueListenableBuilder<bool>(
  valueListenable: AppThemeMode.current,
  builder: (BuildContext context, bool value, Widget? child) {
   // value 매개변수를 통해 현재 mode를 알 수 있음.
   // value = true -> light mode
   // value = false -> dark mode
})
```

# 구현할 사항
- [x] dark mode 세팅
- [x] text theme 세팅

# 참고자료
#1 
https://velog.io/@tygerhwang/Flutter-Light-Dark-%ED%85%8C%EB%A7%88-%EC%A0%81%EC%9A%A9%ED%95%B4-%EB%B3%B4%EA%B8%B0

**Comment by broadenHorizon** [comment]
제가 pr 머지를 해버렸기는 하지만,, riverpod을 활용하면 좋을 것 같아요.
valueListenable이 결국 상태 관리하는 방법이고, AppThemeMode 값이 바뀌면 다시 UI를 그리를 원리인데,
저희가 riverpod을 상태관리 툴로 사용하기로 했어서 더 깔끔하고 일관되게 관리할 수 있을 것 같아요.

아래 riverpod의 notifier를 활용하면 될 것 같고,
https://riverpod.dev/ko/docs/essentials/side_effects
이거는 riverpod + hive(db)를 활용해서 theme color 구현한 riverpod 공홈에 올라온 예시에요
https://github.com/GitGud31/flutter_theme_riverpod_hive/tree/master
근데 riverpod이 최신 버전으로 오면서 구현 방법이 좀 바껴서 첫번째 링크 먼저 읽고 두 번째 읽어서 조금 변형해서 적용하면 될 것 같습니다.

hive 기본 설정은 제가 해놓을게요

**Comment by leesunmin1231** [comment]
네. 첨부해주신 링크 확인해보도록 하겠습니다.

**Comment by leesunmin1231** [comment]
구현 완료
